spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file_csv
    username: root
    password: 4l4n*D4m14n

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect